#!/bin/dash
a=$*
# count=0
# for i in $a
# do
# 	count=$(($count + 1))
# done



# get_state(){
# 	line=$( sed -n "/$1:/p" ./.girt/index.txt )
# 	state=${line#*:}
# 	echo $state
# }

holy(){
	# if file doesn't exist
	if test ! -f ./.girt/tmp/$1
    	then
		echo "not_exist"
		return 0
	fi
    # if not committed
	line=$( sed -n "/$1:/p" ./.girt/index.txt )
	state=${line#*:}
	#echo "file name is $1"
	if test "$state" = "updated" || test "$state" = "added"
	then
	    
		dif=$(diff $1 ./.girt/tmp/$1)
		#if file in working place is same with it in tmp
		if test ${#dif} -eq 0
		then
			#echo "girt-rm: error: '$file' has staged changes in the index"
			echo "not_committed"
			return 0
		else
		    echo "all_different"
			return 0
		fi
	fi
        # if committed but different
	if [ "$state" = "committed" ]
	then
		dif=$(diff $1 ./.girt/tmp/$1)
		if test ${#dif} -gt 0
		then
		echo "different"
			return 0
		fi
	fi
	echo "ok"

}



case $1 in
	"--force")
		# echo "force"
		# if is --force file
		if test ! "$2" = "--cached"
		then
			command=${a#*--force}
			for file in $command
			do
				flag=$(holy "$file")
				case $flag in
				not_exist)
					echo "girt-rm: error: '$file' is not in the girt repository"
					;;
				*)
					rm $file
					rm ./.girt/tmp/$file
					# if never committed,delete the record in index.txt
					tmp=$(ls ./.girt/save/""$file""_*"") 2>/dev/null
					if test ${#tmp} -gt 0
					then
						sed -i "s/$file:.*/$file:deleted/g" ./.girt/index.txt
					else
						sed -i "/.*$file.*/d" ./.girt/index.txt
					fi
					;;
				esac
			done
		fi
		#if is --force --cached
		if test "$2" = "--cached"
		then
			command=${a#*--cached}
			for file in $command
			do
				flag=$(holy "$file")
				case $flag in
				not_exist)
					echo "girt-rm: error: '$file' is not in the girt repository"
					;;
				*)
					# rm $file
					rm ./.girt/tmp/$file
					sed -i "/$file:.*/d" ./.girt/index.txt
					;;
				esac
			done
		fi





		;;
	"--cached")
		# echo "cached"
		command=${a#*--cached}
		#echo $command
		for file in $command
		do
		#	echo $file
			# check if file exist
			# echo $file
			flag=$(holy "$file")
			case $flag in
			not_exist)
				echo "girt-rm: error: '$file' is not in the girt repository"
			;;
			# not_committed)
			# 	echo "girt-rm: error: '$file' has staged changes in the index"
			# ;;
			all_different)
				echo "girt-rm: error: '$file' in index is different to both to the working file and the repository"
			;;
			# different)
			# 	echo "girt-rm: error: '$file' is different to the working file"
			# ;;
			*)
			    # echo "rm $file"
				rm ./.girt/tmp/$file
				#sed -i 's/$file:.*/$file:deleted/g' ./.girt/index.txt
			#	echo delete line
				sed -i "/$file:.*/d" ./.girt/index.txt
				;;
			esac
		done
		;;
	*)
		#echo "1"
		for file in $a
		do
		#	echo $file
			# check if file exist
			flag=$(holy "$file")
			case $flag in
			not_exist)
				echo "girt-rm: error: '$file' is not in the girt repository"
			;;
			not_committed)
				echo "girt-rm: error: '$file' has staged changes in the index"
			;;
			all_different)
				echo "girt-rm: error: '$file' in index is different to both to the working file and the repository"
			;;
			different)
				echo "girt-rm: error: '$file' in the repository is different to the working file"
				;;
			ok)
			    rm $file
				rm ./.girt/tmp/$file
				sed -i "s/$file:.*/$file:deleted/g" ./.girt/index.txt
				;;
			esac
		done

		;;
	
esac
	
