#!/bin/dash
a=$(ls -d .girt) 2> /dev/null
#echo $a
count=0
for i in $a
do
	count=$(($count + 1))
done
if [ "$count" -eq "0" ]
then
	mkdir .girt
cd .girt
	touch index.txt
        mkdir tmp
        mkdir save
	echo "Initialized empty girt repository in .girt"
	
fi
#echo $count
if [ "$count" -gt "0" ]
then 
	echo "girt-init: error: .girt already exists"
fi
