#!/bin/dash
tmp_path="./.girt/tmp/"
save_patn="./.girt/save/"
if test ! -f "./.girt/log.txt" 
then
	touch "./.girt/log.txt"
fi


holym(){
	tmp=$(ls ./.girt/tmp)
	save=$(ls ./.girt/save)
	#nothing to commit
	if test ${#tmp} -eq 0
	then
		line=$( cat ./.girt/index.txt | wc -l)
		if test $line -eq 0
		then
			echo 0
			return 0
		fi
	fi

	#if there is something new in tmp
	for i in $tmp
	do
		iname=""$i"_*"
		num=$(ls ./.girt/save/$iname | wc -w) 2> /dev/null
		if test $num -eq 0 #tmp have something new
		then
	#		echo "come to part1"
			echo 1
			return 0
		fi
	done

	#if there is something new in save
	for i in $save
	do
		iname=${i%_*}
		num=$(ls ./.girt/tmp/$iname | wc -w) 2> /dev/null
		if test $num -eq 0
		then
			echo 2
			return 0
		fi
	done

	#if files name are the same, check if they are the same
	for i in $tmp
	do
	#	echo "come to part3"
		iname=""$i"_*"
		#echo $iname
		latest=$(ls ./.girt/save/$iname | tail -1) # get the latest version
	        #echo $latest
		#dif=$(diff ./.girt/tmp/$i ./.girt/save/$latest)
		dif=$(diff ./.girt/tmp/$i $latest)
		if test ${#dif} -gt 0
		then
			echo 3
			return 0
		fi 
	done
    echo 0

}


#if -m
case "$1" in 
-m)
	flag=$(holym)
#	echo "flag is $flag"
	file=$(ls ./.girt/tmp)
	if test $flag -gt 0
	then
		count=$(cat ./.girt/log.txt | wc -l)
		for i in $file
		do
			newname=""$i"_"$count""
			cp -f ./.girt/tmp/$i ./.girt/save/$newname
		done
	#change the commit number
		word=$2
		if test $count -eq 0
		then
			echo "$count $2" > ./.girt/log.txt
		else
			sed -i "1i $count $2" ./.girt/log.txt
		fi
		echo "Committed as commit $count"

	else
		echo "nothing to commit"
	fi




	# change the state into commited
	for i in $file
	do
		sed -i "s/$i:.*/$i:committed/g" ./.girt/index.txt
	done

	# if file is deleted, clear the record of this file in index
	sed -i "/.*deleted.*/d" ./.girt/index.txt
	;;

-a)
# check if all files in index.txt exist
index=$(cat ./.girt/index.txt)
file_exist=1
for i in $index
do
	filename=${i%:*}
	if test ! -f "$filename"
	then
		file_exist=0
		break
	fi
done	
#echo "all file exist"
#  all files exist, check if there is difference between work file and save file
if test $file_exist -eq 1
then
	change=0  # if the files not changed
	version=$(cat ./.girt/log.txt | wc -l)
	last=$(($version-1))
	for i in $index
	do
		filename=${i%:*}
		#echo $filename 
		lastname=""$filename"_"$last""
		# if file in save not exist
		if test ! -f ./.girt/save/$lastname 
		then
			#echo "file name is $lastname"
			#echo "file not in save yet"
			change=1
			break
		fi
	        #it the file exist
		tmp=$(diff $filename ./.girt/save/$lastname)
		if test ${#tmp} -gt 0
		then
			change=1
			break
		fi
	done
	# if there is change,copy all files to tmp and save and rename
	if test $change -eq 1
	then
		for i in $index
		do
			filename=${i%:*}
			newname=""$filename"_"$version""
			cp -f $filename ./.girt/tmp
			cp -f $filename ./.girt/save/$newname
			sed -i "s/$filename:.*/$filename:committed/g" ./.girt/index.txt
		done
		# print the commit and change log.txt
		#change the commit number
	       	#count=$(cat ./.girt/save/log.txt | wc -l)
        	if test $version -eq 0
	       	then
			echo "$version $3" >> ./.girt/log.txt
       		else
			sed -i "1i $version $3" ./.girt/log.txt
		fi
		echo "Committed as commit $version"
	else
		# no change has been made, do nothing
		echo "girt-commit: error: nothing to commit"
	fi
fi
#echo "gg"
;;

esac
