#!/bin/dash
file=$*

exist(){
	# normally. flag=1,file exist
	flag=1
	if test ! -f $1
	then
		flag=0 # if not exist
		index=$(cat ./.girt/index.txt)
		for i in $index
		do
			name=${i%:*}
			if test "$name" = "$1"
			then
				flag=2 # if is a deleted file,flag=2
			 	echo $flag
				return 0
			fi
		done
	fi	
	echo $flag
	return 0
}

add_exist(){
	if test ! -f ./.girt/tmp/$1
	then
		echo 1  # if the file exist in index but not in tmp, it's a deleted file
		# change the state to added
		return 0
	fi

	#if exist in tmp
	dif=$(diff $1 ./.girt/tmp/$1)
	if test ${#dif} -gt 0 # if different
	then
		echo 2 #change state to updated
	else    	
		echo 0 #file is the same, change nothing
	fi
}



# if .girt not exist
if test ! -d ".girt"
then
echo "girt-add: error: girt repository directory .girt not found"
return 1
fi



index=$(cat ./.girt/index.txt)

for i in $file
do
	flag=$(exist "$i")
       	#echo $flag
	# if not exist and not deleted
	if test $flag -eq 0
	then
		echo "girt-add: error: can not open 'non_existent_file'"
		continue
	fi
	
	# if exist 
	if test $flag -eq 1
	then
		#old_IFS=$IFS
		point=1
		for j in $index
		do
			name=${j%:*}
			if test "$i" = "$name"  # if the name is in index
			then
			    motion=$(add_exist "$i")
				#echo flag is $motion
				if test $motion -eq 2  # if new file is different from old file
				then
					#echo  different
					sed -i "s/$i:.*/$i:updated/g" ./.girt/index.txt
					point=0
					cp -f "$i" ./.girt/tmp
					break
				fi

				if test $motion -eq 1 #if it's a deleted file
				then
					sed -i "s/$i:.*/$i:added/g" ./.girt/index.txt
					point=0
					cp -f "$i" ./.girt/tmp
					break
				fi
				if test $motion -eq 0 # if nothing will be changed
				then 
					point=0
				fi
				
			fi
		done
		if test $point -eq 1
		then
			echo "$i:added" >> ./.girt/index.txt
			cp -f "$i" ./.girt/tmp
		fi
	fi
	
	# if file is a deleted file
	if test $flag -eq 2
	then
		sed -i "s/$i:.*/$i:deleted/g" ./.girt/index.txt
		rm ./.girt/tmp/$i	
	fi

done




